favorite:
  drink: coffee
  food: pizza

pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions


sub-test:
  dessert: ice cream
  hello: from-sub

global:
  salad: caesar

hello: from-parent
