kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cfgmap2
  {{- template "my-templ" . }}
data:
  dessert: {{ .Values.dessert }}
  salad: {{ .Values.global.salad }}
  hello: {{ .Values.hello }}
